var CLOSURE_UNCOMPILED_DEFINES = {"figwheel.repl.connect_url":"ws:\/\/localhost:9500\/figwheel-connect?fwprocess=baa2e6&fwbuild=background"};
var CLOSURE_NO_DEPS = true;
if(typeof goog == "undefined") document.write('<script src="compiled/background/goog/base.js"></script>');
document.write('<script src="compiled/background/goog/deps.js"></script>');
document.write('<script src="compiled/background/cljs_deps.js"></script>');
document.write('<script>if (typeof goog == "undefined") console.warn("ClojureScript could not load :main, did you forget to specify :asset-path?");</script>');
document.write('<script>goog.require("devtools.preload");</script>');
document.write('<script>goog.require("figwheel.core");</script>');
document.write('<script>goog.require("figwheel.main");</script>');
document.write('<script>goog.require("figwheel.repl.preload");</script>');
document.write('<script>goog.require("process.env");</script>');
document.write('<script>goog.require("chromex_sample.background");</script>');
